/**
 * The second wave's report. Reached only through `report.mjs --wave=2`, never run on its own.
 *
 * WHY IT WRITES SOMEWHERE ELSE, AND WHY THAT IS NOT TIDINESS. The wave 1 document is generated from
 * `runs/` and CI compares it byte for byte. A wave 2 file dropped into that directory would
 * recompute the frozen preregistered metric over a mixed population and quietly change a published
 * result. So wave 2 reads `runs-wave2/` and writes `results-wave2.md`, and the wave 1 path is not
 * touched at all: its output hash is asserted unchanged in the same commit that added this file.
 *
 * WHAT IT CANNOT DO. It cannot overturn wave 1 and does not try. Only two catalogue rows read a
 * page's own tools and the preregistered threshold was three, so even a clean sweep here is a
 * median of two. What it CAN answer is the one question wave 1 could not reach: do those two rows
 * return DIFFERENT verdicts on DIFFERENT pages.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const RUNS2 = path.join(HERE, 'runs-wave2');
const OUT2 = path.join(HERE, 'results-wave2.md');
const SETTLED = new Set(['pass', 'fail', 'by-design']);

function loadRuns(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => ({ file: f, data: JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')) }));
}

const runs = loadRuns(RUNS2);
const out = [];

out.push('# Second wave: what happened when the pages’ own read only tools were called');
out.push('');
out.push('**Generated by `node evidence/impact/report.mjs --wave=2`. Do not edit by hand; CI compares');
out.push('this file with a fresh run byte for byte.**');
out.push('');
out.push('**Post hoc, and labelled as such. It does not change the preregistered result in');
out.push('`results.md`, and it could not: only two catalogue rows read a page’s own tools and the');
out.push('preregistered threshold was three. The primary metric and its threshold are untouched.**');
out.push('');

if (!runs.length) {
  out.push('## No second wave runs exist yet');
  out.push('');
  out.push('`evidence/impact/runs-wave2/` is empty, so there is nothing to report. This file exists so');
  out.push('that its absence cannot be mistaken for a result.');
} else {
  const byRow = {};
  for (const r of runs) {
    const row = r.data.behaviour || 'unknown';
    const finding = (r.data.result && (r.data.result.findings || []).find((x) => x.id === row)) || null;
    (byRow[row] = byRow[row] || []).push({ id: r.data.corpusId, finding, data: r.data });
  }
  const rows = Object.keys(byRow).sort();
  const pages = new Set(runs.map((r) => r.data.corpusId));

  out.push('## The answer wave 1 could not reach');
  out.push('');
  out.push(`Authorised on **${pages.size} pages**, the ones wave 1 recorded as publishing at least one`);
  out.push('tool they annotated `readOnlyHint`. Two rows, run separately.');
  out.push('');
  for (const row of rows) {
    const got = byRow[row].filter((x) => x.finding);
    const verdicts = new Set(got.map((x) => x.finding.verdict));
    const settled = got.filter((x) => SETTLED.has(x.finding.verdict));
    out.push(`- **\`${row}\`** ran on ${byRow[row].length}, reached a verdict on ${got.length}, `
      + `**settled on ${settled.length}**, and returned **${verdicts.size} distinct `
      + `verdict${verdicts.size === 1 ? '' : 's'}**`
      + `${verdicts.size ? `: ${[...verdicts].sort().map((v) => `\`${v}\``).join(', ')}` : ''}.`);
  }
  out.push('');

  const discriminating = rows.filter((row) => {
    const got = byRow[row].filter((x) => x.finding);
    return new Set(got.map((x) => x.finding.verdict)).size > 1;
  });
  const anySettled = rows.some((row) => byRow[row]
    .some((x) => x.finding && SETTLED.has(x.finding.verdict)));

  if (discriminating.length) {
    out.push(`**${discriminating.length} row(s) told one page from another: `
      + `${discriminating.map((r) => `\`${r}\``).join(', ')}.** So the execution half is not blind to`);
    out.push('the page. In wave 1 it was switched off by that run’s own read only default, which is');
    out.push('the preregistration defect already recorded in `protocol.md`, not a limit on reach.');
  } else if (anySettled) {
    out.push('**Neither row told one page from another.** Authorising the calls changed what these');
    out.push('rows say, and did not change whether they discriminate between pages.');
  } else {
    out.push('**Neither row settled anywhere, so neither could discriminate.** Authorising the calls');
    out.push('changed the reason for the abstention and nothing else, and the reasons are printed');
    out.push('below rather than summarised away.');
  }
  out.push('');

  out.push('## Every run, including the ones that settled nothing');
  out.push('');
  out.push('| page | row | read only tools authorised | verdict | ms | exit |');
  out.push('|---|---|---|---|---|---|');
  for (const row of rows) {
    for (const x of [...byRow[row]].sort((a, b) => a.id.localeCompare(b.id))) {
      out.push(`| \`${x.id}\` | ${row} | ${(x.data.authorisedTools || []).length} | `
        + `${x.finding ? x.finding.verdict : 'no verdict'} | ${x.data.elapsedMs} | ${x.data.exitCode} |`);
    }
  }
  out.push('');

  out.push('## What each run actually observed, in its own words');
  out.push('');
  for (const row of rows) {
    for (const x of [...byRow[row]].sort((a, b) => a.id.localeCompare(b.id))) {
      if (!x.finding) {
        out.push(`- \`${x.id}\` **${row}**: no verdict. `
          + `${String(x.data.stderr || '').replace(/\s+/g, ' ').trim().slice(0, 300) || 'no stderr recorded'}`);
        continue;
      }
      const said = String(x.finding.observed || x.finding.reason || '').replace(/\s+/g, ' ').trim();
      /*
       * THE ROW'S OWN ERROR LINE, WHEN IT HAS ONE.
       *
       * P6 abstained on three pages and its verdict reason read "the transcript carries no
       * observation for this behaviour", which is true and says nothing. The measured reason was
       * sitting in transcript.errors the whole time: one read only tool, and a differential needs
       * two. An abstention is a result, so it gets the same treatment as a verdict.
       */
      const errs = ((x.data.transcript && x.data.transcript.errors) || [])
        .filter((e) => String(e).startsWith(`${row}:`))
        .map((e) => String(e).slice(row.length + 1).replace(/\s+/g, ' ').trim());
      out.push(`- \`${x.id}\` **${row} ${x.finding.verdict}**: ${said.slice(0, 420)}`
        + (errs.length ? ` **Why it could not run:** ${errs.join(' ')}` : ''));
    }
  }
  out.push('');

  out.push('## Exactly which tools were authorised');
  out.push('');
  out.push('Selected by a rule rather than by hand: every wave 1 page that published at least one tool');
  out.push('it annotated `readOnlyHint`. The selection rule is the authorisation rule, so the set can');
  out.push('be re-derived from the wave 1 run files instead of trusted.');
  out.push('');
  const named = new Set();
  for (const row of rows) {
    for (const x of [...byRow[row]].sort((a, b) => a.id.localeCompare(b.id))) {
      if (named.has(x.id)) continue;
      named.add(x.id);
      const tools = (x.data.authorisedTools || []).map((t) => `\`${t}\``).join(', ');
      out.push(`- \`${x.id}\`: ${tools || 'none'}`);
    }
  }
  out.push('');

  out.push('## What a reader must not take from this');
  out.push('');
  out.push('- **`readOnlyHint` is the page’s own claim about itself, and this suite does not verify');
  out.push('  it.** `src/probe/steps.js` calls it an annotation this suite exists to doubt. The');
  out.push('  guarantee is the narrower one: nothing outside a page’s own declared read only set was');
  out.push('  ever called, enforced in `src/probe/observe.js` by a strict `=== true`.');
  out.push('- The filter reads a snapshot taken before anything was registered, while the object that');
  out.push('  gets invoked is resolved live by name. A page that re-registered a name mid run would');
  out.push('  defeat it. None of these pages does, and that is an observation about four commits');
  out.push('  rather than a property of the instrument.');
  out.push('- Every page ran from an exact commit served on loopback, with no credential in the child');
  out.push('  environment. No form was submitted, no page is named as defective, and no maintainer was');
  out.push('  contacted.');
  out.push('');

  out.push('## Provenance');
  out.push('');
  out.push('| page | row | source commit | instrument commit | authorisation |');
  out.push('|---|---|---|---|---|');
  for (const row of rows) {
    for (const x of [...byRow[row]].sort((a, b) => a.id.localeCompare(b.id))) {
      out.push(`| \`${x.id}\` | ${row} | \`${String(x.data.sourceCommit).slice(0, 12)}\` | `
        + `\`${String(x.data.toolCommit).slice(0, 12)}\` | ${x.data.authorisation} |`);
    }
  }
}

out.push('');
out.push('## Artifact hashes');
out.push('');
out.push('| file | sha256 |');
out.push('|---|---|');
for (const r of runs) {
  const bytes = fs.readFileSync(path.join(RUNS2, r.file));
  out.push(`| \`runs-wave2/${r.file}\` | \`${crypto.createHash('sha256').update(bytes).digest('hex')}\` |`);
}
out.push('');

const text = out.join('\n');

if (process.argv.includes('--check')) {
  const committed = fs.existsSync(OUT2) ? fs.readFileSync(OUT2, 'utf8') : '';
  if (committed.split('\r\n').join('\n') !== text) {
    console.error('results-wave2.md is not what the wave 2 runs produce. Regenerate it:');
    console.error('  node evidence/impact/report.mjs --wave=2');
    process.exit(1);
  }
  console.log(`results-wave2.md matches ${runs.length} run file(s).`);
  process.exit(0);
}

fs.writeFileSync(OUT2, text);
console.log(`wrote results-wave2.md from ${runs.length} run file(s).`);
