#!/usr/bin/env node
/**
 * The deployment identity: every file the live page loads, with a hash of each.
 *
 * WHY A MANIFEST AND NOT A COMMIT MARKER. The obvious way to bind a deployment is to stamp the
 * commit SHA into the page, and it cannot be done here: the SHA is not known until the commit
 * exists, and writing it afterwards makes the deployed bytes differ from the tree, which is the
 * exact drift the check is for. A content manifest has no such circularity. It is generated from
 * the tree, committed with it, served with it, and it is the thing the live verifier compares
 * against.
 *
 * WHAT IT BINDS, and it is three directions rather than one:
 *
 *   1. the manifest matches the working tree      asserted by tests/unit/manifest.test.js
 *   2. every served file matches the manifest     asserted by readiness row R5, over the network
 *   3. the manifest covers the whole graph        asserted by both, from scripts/runtime_graph.mjs
 *
 * Direction 3 is the one that matters most. Row R5 used to compare one file, `behaviours.js`, while
 * eight others were served unverified, and nothing said so because the list was written by hand.
 * The list is now walked from `index.html`, so a module reached by a new import joins it with
 * nobody deciding anything.
 *
 * NEWLINES ARE NORMALISED BEFORE HASHING, and that is a real decision rather than convenience. This
 * repository is developed on Windows with `core.autocrlf`, so the working tree holds CRLF and
 * GitHub Pages serves LF. Measured on one file: 421 line endings, 421 bytes, identical after
 * normalisation. Hashing raw bytes would make every row fail for a difference that is not a
 * difference in what a browser executes. Nothing else is normalised: a changed character, a changed
 * space inside a line, a changed order all still fail.
 *
 *   node scripts/build_manifest.mjs           write runtime-manifest.json
 *   node scripts/build_manifest.mjs --check    exit 1 if it is out of date, and say what changed
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

import { runtimeGraph } from './runtime_graph.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const MANIFEST_PATH = 'runtime-manifest.json';

/** The hash a file gets, over its bytes with line endings normalised and nothing else changed. */
export function hashOf(text) {
  return crypto.createHash('sha256').update(String(text).replace(/\r\n/g, '\n'), 'utf8').digest('hex');
}

/** Build the manifest from the working tree. */
export function buildManifest(root = ROOT) {
  const { files, unresolved, refused } = runtimeGraph(root);
  const entries = {};
  for (const relative of files) {
    if (relative === MANIFEST_PATH) continue;
    entries[relative] = hashOf(fs.readFileSync(path.join(root, relative), 'utf8'));
  }
  return {
    // A note to whoever opens this file expecting a build artifact.
    note: 'Generated by scripts/build_manifest.mjs from the module graph starting at index.html. '
      + 'Readiness row R5 fetches every path below from the live origin and compares. '
      + 'Hashes are sha256 over the file with line endings normalised to LF.',
    entryPoint: 'index.html',
    fileCount: Object.keys(entries).length,
    unresolved,
    refused,
    files: entries,
  };
}

/** Read the committed manifest, or null. */
export function readManifest(root = ROOT) {
  const p = path.join(root, MANIFEST_PATH);
  if (!fs.existsSync(p)) return null;
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; }
}

/** What differs between a freshly built manifest and a stored one. */
export function manifestDrift(fresh, stored) {
  if (!stored) return ['there is no committed manifest at all'];
  const drift = [];
  const freshFiles = fresh.files || {};
  const storedFiles = stored.files || {};
  for (const key of Object.keys(freshFiles)) {
    if (!(key in storedFiles)) drift.push(`${key} is in the graph and not in the manifest`);
    else if (storedFiles[key] !== freshFiles[key]) drift.push(`${key} has changed since the manifest was written`);
  }
  for (const key of Object.keys(storedFiles)) {
    if (!(key in freshFiles)) drift.push(`${key} is in the manifest and no longer in the graph`);
  }
  return drift;
}

const invokedDirectly = process.argv[1]
  && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (invokedDirectly) {
  const fresh = buildManifest();
  if (fresh.unresolved.length) {
    console.error('build_manifest: the page references files that are not in the tree:');
    for (const u of fresh.unresolved) console.error(`  - ${u.from} references ${u.reference}`);
    process.exit(1);
  }
  // A refusal is a thing a browser would load and this walk cannot follow. Guessing would put a
  // manifest on the origin that describes something other than what is served.
  if (fresh.refused.length) {
    console.error('build_manifest: the page does something this graph cannot follow:');
    for (const r of fresh.refused) console.error(`  - ${r}`);
    process.exit(1);
  }
  if (process.argv.includes('--check')) {
    const drift = manifestDrift(fresh, readManifest());
    if (drift.length) {
      console.error(`build_manifest: the manifest is out of date, ${drift.length} differences:`);
      for (const line of drift) console.error(`  - ${line}`);
      console.error('Run: node scripts/build_manifest.mjs');
      process.exit(1);
    }
    console.log(`build_manifest: the manifest is current, ${fresh.fileCount} runtime files.`);
    process.exit(0);
  }
  fs.writeFileSync(path.join(ROOT, MANIFEST_PATH), `${JSON.stringify(fresh, null, 1)}\n`);
  console.log(`build_manifest: wrote ${MANIFEST_PATH} covering ${fresh.fileCount} runtime files.`);
  for (const key of Object.keys(fresh.files)) console.log(`  ${key}`);
}
