/**
 * The readiness thresholds and the surfaces the gate checks, in one importable place.
 *
 * WHY THE NUMBERS LIVE HERE AND ALSO IN A FIXTURE. A threshold written once can be edited to make a
 * red build green, and the edit looks like any other diff. So each number below is pinned again in
 * `THRESHOLD_FIXTURE` at the bottom of this file, the validator asserts the two agree before it
 * runs a single check, and tests/unit/readiness_thresholds.test.js asserts it a third time from
 * outside. Moving a threshold now means changing three things that are visibly about the same
 * number, which is the point: widening a gate should be hard to do by accident and impossible to do
 * quietly.
 *
 * THE RULE THIS ENCODES: never widen a gate, move a threshold or flip a check fail open. Fix
 * reality or state the limitation.
 */

/** The live judge URL. Every mandatory network row is measured against this and nothing else. */
export const LIVE_URL = 'https://upgradedev.github.io/ninthtool/';

/** The repository, for the licence and visibility rows. */
export const REPO = 'upgradedev/ninthtool';

/**
 * Paths on the live origin that must each answer 200, beyond the ones the manifest lists.
 *
 * THIS LIST USED TO BE THE WHOLE ANSWER AND IT WAS HAND MAINTAINED, which is the failure this
 * repository has now had three times: a list somebody must remember to update is a list that goes
 * stale. Rows M6 and R5 now take the file list from `runtime-manifest.json`, which is generated by
 * walking the module graph from index.html, so a module reached by a new import is covered with
 * nobody deciding anything.
 *
 * What remains here is the two things a graph walk cannot know: that the origin root serves the
 * page, and that the manifest itself is served.
 */
export const LIVE_PATHS = ['', 'runtime-manifest.json'];

/** The deployment identity the live rows fetch and compare against. */
export const MANIFEST_PATH = 'runtime-manifest.json';

/**
 * Tool names the page must actually register, checked against the DEPLOYED bytes rather than the
 * source. Grepping the source proves what we wrote; grepping what is served proves what a judge
 * gets. Those have differed before.
 */
export const CLAIMED_TOOLS = ['nt_list_behaviours', 'nt_explain_behaviour', 'nt_run_audit', 'nt_get_findings'];

/** The sentence that must appear, word for word, on the live page and in the README. */
export const FLAGSHIP = "Ninth Tool executes your page's WebMCP tools in the browser and shows which "
  + 'promises the standard silently drops, with the command that reproduces each one.';

/** Every mandatory row must pass. There is no partial credit on a mandatory row. */
export const MANDATORY_PASS_RATE = 1.0;

/** Across every automated row, this fraction must pass or the gate exits non zero. */
export const OVERALL_PASS_RATE = 0.95;

/** The cap the video must come in under, in seconds, from the rules. */
export const VIDEO_MAX_SECONDS = 180;

/**
 * The second pinning of every number above.
 *
 * The validator compares this to the exported constants before running anything and refuses to run
 * when they disagree. Change one and the gate stops, which is the behaviour we want from a
 * threshold that somebody is quietly moving.
 */
export const THRESHOLD_FIXTURE = Object.freeze({
  MANDATORY_PASS_RATE: 1.0,
  OVERALL_PASS_RATE: 0.95,
  VIDEO_MAX_SECONDS: 180,
  LIVE_URL: 'https://upgradedev.github.io/ninthtool/',
  REPO: 'upgradedev/ninthtool',
  CLAIMED_TOOL_COUNT: 4,
  LIVE_PATH_COUNT: 2,
});

/**
 * Refuse to run when the two copies disagree.
 * @returns {string[]} the disagreements, empty when they agree
 */
export function thresholdDrift() {
  const drift = [];
  const check = (name, live, pinned) => {
    if (live !== pinned) drift.push(`${name}: config says ${live}, the fixture says ${pinned}`);
  };
  check('MANDATORY_PASS_RATE', MANDATORY_PASS_RATE, THRESHOLD_FIXTURE.MANDATORY_PASS_RATE);
  check('OVERALL_PASS_RATE', OVERALL_PASS_RATE, THRESHOLD_FIXTURE.OVERALL_PASS_RATE);
  check('VIDEO_MAX_SECONDS', VIDEO_MAX_SECONDS, THRESHOLD_FIXTURE.VIDEO_MAX_SECONDS);
  check('LIVE_URL', LIVE_URL, THRESHOLD_FIXTURE.LIVE_URL);
  check('REPO', REPO, THRESHOLD_FIXTURE.REPO);
  check('CLAIMED_TOOL_COUNT', CLAIMED_TOOLS.length, THRESHOLD_FIXTURE.CLAIMED_TOOL_COUNT);
  check('LIVE_PATH_COUNT', LIVE_PATHS.length, THRESHOLD_FIXTURE.LIVE_PATH_COUNT);
  return drift;
}
